backend:
  name: git-gateway
  branch: main
media_folder: "public/uploads"
public_folder: "/uploads"
collections:
  - name: "photos"
    label: "Photos"
    folder: "src/content/photos"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Free", name: "free", widget: "boolean", default: false }
  - name: "videos"
    label: "Videos"
    folder: "src/content/videos"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Video URL", name: "url", widget: "string" }
      - { label: "Free", name: "free", widget: "boolean", default: false }
  - name: "products"
    label: "Shop Products"
    folder: "src/content/products"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Price (INR)", name: "price", widget: "number" }
      - { label: "Affiliate Link", name: "link", widget: "string" }
  - name: "items"
    label: "Personal Items"
    folder: "src/content/items"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Price (INR)", name: "price", widget: "number" }
      - { label: "Description", name: "description", widget: "text" }
